# Generated by Django 2.2.1 on 2019-07-21 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Эл.почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(max_length=256, verbose_name='Адрес')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий к заказу')),
                ('total_number', models.SmallIntegerField(default=1, verbose_name='Общее количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая стоимость')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('status', models.SmallIntegerField(choices=[(1, 'Новый'), (2, 'Оплачено'), (3, 'Выполняется'), (4, 'Отправлен'), (5, 'Выполнен'), (6, 'Отменён')], default=1, verbose_name='Статус заказа')),
                ('customer', models.ForeignKey(on_delete=models.SET('---'), to='shop.Customers', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Категория товара')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование товара')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Количество на складе')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('short_text', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='В продаже')),
                ('is_top', models.BooleanField(default=False, verbose_name='Топ')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductBrand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'index_together': {('category', 'is_active', 'is_top')},
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Содержание')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отзыв на товар',
                'verbose_name_plural': 'Отзывы на товар',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64, verbose_name='Товар')),
                ('number_of_units', models.SmallIntegerField(default=1, verbose_name='Количество')),
                ('price_of_unit', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Заказанные товары',
                'ordering': ['product'],
            },
        ),
    ]
