# Generated by Django 2.2.1 on 2019-08-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190802_0701'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
