# Generated by Django 2.2.1 on 2019-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190706_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='top_products',
            field=models.ManyToManyField(to='shop.Products'),
        ),
    ]
