# Generated by Django 2.2.1 on 2019-07-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcategory_top_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='top_products',
        ),
        migrations.AddField(
            model_name='products',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице?'),
        ),
    ]
