# Generated by Django 2.2.1 on 2019-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190707_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['created', 'status'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='total_number',
            field=models.SmallIntegerField(default=1, verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Топ'),
        ),
    ]
