# Generated by Django 2.2.1 on 2019-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190708_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinorder',
            options={'ordering': ['product'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В продаже'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая стоимость'),
        ),
    ]
