# Generated by Django 2.2.1 on 2019-07-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190710_2302'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together={('category', 'is_active', 'is_top')},
        ),
    ]
