# Generated by Django 2.2.1 on 2019-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Номер маршрута')),
            ],
            options={
                'verbose_name': 'Номер маршрута',
                'verbose_name_plural': 'Номера маршрутов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название остановки, адрес')),
                ('latitude', models.FloatField(default=0, verbose_name='Широта')),
                ('longitude', models.FloatField(default=0, verbose_name='Долгота')),
                ('routes', models.ManyToManyField(to='mapofstops.Route', verbose_name='Номера маршрутов')),
            ],
            options={
                'verbose_name': 'Автобусная остановка',
                'verbose_name_plural': 'Автобусные остановки',
                'ordering': ['name'],
            },
        ),
    ]
