# Generated by Django 2.2.1 on 2019-08-02 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий к заказу')),
                ('total_number', models.SmallIntegerField(default=1, verbose_name='Общее количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая стоимость')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('status', models.SmallIntegerField(choices=[(1, 'Новый'), (2, 'Оплачено'), (3, 'Выполняется'), (4, 'Отправлен'), (5, 'Выполнен'), (6, 'Отменён')], default=1, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64, verbose_name='Товар')),
                ('number_of_units', models.SmallIntegerField(default=1, verbose_name='Количество')),
                ('price_of_unit', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Заказанные товары',
                'ordering': ['product'],
            },
        ),
    ]
