# Generated by Django 2.2.1 on 2019-06-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190616_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите рубрику', max_length=30, verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Основная')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Rubric')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='rubrics',
            field=models.ManyToManyField(help_text='Укажите рубрику', through='articles.Relations', to='articles.Rubric', verbose_name='Рубрика'),
        ),
    ]
