# Generated by Django 2.2.1 on 2019-06-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Фирма производитель',
                'verbose_name_plural': 'Фирмы производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('os', models.CharField(max_length=15, verbose_name='Операционная система')),
                ('typesim', models.CharField(max_length=15, verbose_name='Тип SIM-карт')),
                ('numsim', models.CharField(max_length=1, verbose_name='Количество SIM-карт')),
                ('screendiag', models.CharField(max_length=8, verbose_name='Диагональ экрана')),
                ('screenres', models.CharField(max_length=10, verbose_name='Разрешение экрана')),
                ('density', models.CharField(max_length=8, verbose_name='Плотность пикселей')),
                ('proc', models.CharField(max_length=30, verbose_name='Процессор')),
                ('memory', models.CharField(max_length=5, verbose_name='Объём оперативной памяти')),
                ('nfc', models.BooleanField(default=False, verbose_name='NFC')),
                ('glonas', models.BooleanField(default=False, verbose_name='ГЛОНАСС')),
                ('gps', models.BooleanField(default=False, verbose_name='GPS')),
                ('fmradio', models.BooleanField(default=False, verbose_name='FM-Радио')),
                ('vendorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
                'ordering': ['vendorname', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.TextField(blank=True, help_text='Дополнительные особенности и уникальные характеристики', null=True, verbose_name='Дополнительно')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.TextField(blank=True, help_text='Дополнительные особенности и уникальные характеристики', null=True, verbose_name='Дополнительно')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Asus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.TextField(blank=True, help_text='Дополнительные особенности и уникальные характеристики', null=True, verbose_name='Дополнительно')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
        ),
    ]
