# Generated by Django 2.2.1 on 2019-06-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='is_subscribe',
        ),
    ]
