# Generated by Django 2.2.1 on 2019-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_advuser_is_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписался?'),
        ),
    ]
