# Generated by Django 2.2.1 on 2019-06-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_advuser_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='subscribe',
            new_name='is_subscribe',
        ),
    ]
