# Generated by Django 2.2.1 on 2019-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='counts',
            field=models.IntegerField(default=0, verbose_name='Счётчик попыток'),
        ),
    ]
