# Generated by Django 2.2.1 on 2019-06-27 10:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filecsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=30, verbose_name='Путь к файлу')),
            ],
            managers=[
                ('wrk_path', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Модель')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('release_date', models.DateField(verbose_name='Дата  релиза')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='Наличие LTE')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
