# Generated by Django 2.2.1 on 2019-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields_for_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Имя поля')),
                ('width', models.SmallIntegerField(verbose_name='ширина поля')),
            ],
        ),
    ]
