# Generated by Django 2.2.1 on 2019-06-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields_for_table',
            new_name='Fieldsfortable',
        ),
    ]
