# Generated by Django 2.2.1 on 2019-06-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_fields_for_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields_for_table',
            options={'verbose_name': 'Поле таблицы', 'verbose_name_plural': 'Поля для таблицы'},
        ),
    ]
