# Generated by Django 2.2.1 on 2019-06-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20190627_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AlterModelOptions(
            name='fields_for_table',
            options={'ordering': ['id'], 'verbose_name': 'Поле таблицы', 'verbose_name_plural': 'Поля для таблицы'},
        ),
    ]
